name: Backup Postman Collection Details

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次
  workflow_dispatch:  # 手动触发

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch Postman Collections UIDs
        run: |
          curl --location --request GET 'https://api.getpostman.com/collections' \
          --header 'X-Api-Key: ${{ secrets.POSTMAN_API_KEY }}' > collections.json
          cat collections.json | jq -r '.collections[].uid' > collection_uids.txt

      - name: Fetch Postman Collection Details
        run: |
          mkdir -p collection_details
          while read uid; do
          curl --location --request GET "https://api.getpostman.com/collections/$uid" \
          --header "X-Api-Key: ${{ secrets.POSTMAN_API_KEY }}" > collection_details/$uid.json
          done < collection_uids.txt

      - name: Configure Git to Use GitHub token
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Commit and Push Changes
        run: |
          git config --global user.email "z04jp6w944@gmail.com"
          git config --global user.name "z04jp6w94"
          git add collection_details/*.json
          git commit -m "Backup Postman Collection Details"
          git push
      # 追蹤未追蹤的文件
      #- name: Add untracked files
      #  run: |
      #    git add collection_uids.txt collections.json

      - name: Add and commit all changes
        run: |
          git add -A
          git commit -m "Backup Postman collections"
